import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import ThemedNotification from "@/components/ThemedNotification";
import NavbarWrapper from "@/components/LandingPage/NavbarWrapper";
import FooterWrapper from "@/components/LandingPage/FooterWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Code Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className="scroll-p-20 scroll-smooth"
        suppressHydrationWarning
      >
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col min-h-screen">
              <NavbarWrapper />
              <main className="flex-grow">{children}</main>
              <FooterWrapper />
            </div>
            <ThemedNotification />
          </ThemeProvider>
          {/* <Toaster richColors theme="system"/> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
